// <auto-generated />
namespace S2021A6CXY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class trackclipcontentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trackclipcontentType));
        
        string IMigrationMetadata.Id
        {
            get { return "202108080236242_track-clip-contentType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
